### ISSUE TITLE
Change documentation system to DocFX

### ISSUE THREAD

**Issue by jkoritzinsky** [robotdotnet/WPILib#105]
DocFX is simpler than Sandcastle and has official support from Microsoft. Additionally, the search/filter function is Javascript-based, so it will work even when we host on GitHub Pages. It also looks better.

**Comment by ThadHouse** [comment]
That looks really cool. Glad to see an officially supported documentation tool from microsoft again.

**Comment by ThadHouse** [comment]
It still looks like we're going to need the individual sandcastle projects to generate the xml docs, but that's fairly easy as that does not require maintaining. But it would for sure be nice to get the site completely moved over.

**Comment by ThadHouse** [comment]
Got this started over on the https://github.com/robotdotnet/WPILib-Docs repo. Sandcastle didn't support building web docs for project.json, so we had to move. This is much easier however.
