### ISSUE TITLE
CANTalon and other removed classes

### ISSUE THREAD

**Issue by msoucy** [robotdotnet/WPILib#112]
As of 2017, the CANTalon and other classes were removed from the library. The comment for fb5fecc7a037daa7e2da3a837bcc54e73a35238d states that they will be moved to another location, but no replacement location has been given.

**Comment by ThadHouse** [comment]
Grab the FRC.WPILib.CTRE package off of Nuget. I'll update the docs tonight. Sorry about that.

**Comment by ThadHouse** [comment]
That should be the only removed class. Anything else missing that you need?

**Comment by msoucy** [comment]
That appears to be all that we need at the moment. Thank you!

**Comment by ThadHouse** [comment]
https://robotdotnet.github.io/tutorials/ctre.html

I added a page to the docs about this. Thanks for reminding me!

**Comment by msoucy** [comment]
For history's sake - this was done in robotdotnet/WPILib-Docs@aed54c5
