### ISSUE TITLE
Figure out NuGet.

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/WPILib#12]
It would be great to use NuGet to distribute the WPILib. It doesnt seem too difficult, but we would need to figure out how to implement it.

**Comment by jkoritzinsky** [comment]
How would you feel about creating a MyGet feed for HAL and the WPILib?

**Comment by ThadHouse** [comment]
Sure that should work. Looks like an easy way to get everything set up.

**Comment by ThadHouse** [comment]
I got a MyGet feed working, and pushed a few builds to it. Is seems to work pretty good. The feed is located here

https://www.myget.org/F/robotdotnet/api/v2

**Comment by ThadHouse** [comment]
Done. We have a myget feed for building the code, and an actual nuget feed for hosting the release packages. It was easier just to build release packages and upload them to nuget manually, then to deal with some of the issues in myget. But it still works OK for a build server. Would be nice if it checked pull requests though.
