### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by ThadHouse** [robotdotnet/WPILib#33]
Currently doesnt show examples and remarks. This means I can't download from nuget. Instead I have to download from github.

**Comment by stinethebean** [comment]
Hey @ThadHouse & @jkoritzinsky , couldn't find a better way to contact you. Would you be up for a discussion on partnering with Microsoft on making robotdotnet even more amazing?  I'm one of the FRC leads here at Microsoft. If you're interested, please email me at Christine.Matheney@Microsoft.com  :)

**Comment by ThadHouse** [comment]
I sent you an email. I would be very interested in working with Microsoft directly.

**Comment by jkoritzinsky** [comment]
I also sent you an email stating the same thing.

**Comment by ThadHouse** [comment]
This is done, so closing.
